# Generated by Django 6.0 on 2026-08-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employeeprofile_email_verified_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='google_sub',
            field=models.CharField(blank=True, help_text='Google account subject (sub) claim', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='avatar',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
