# Generated by Django 4.2.28 on 2026-09-15 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_leavebalance_last_renewed_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('payslip', 'Fiche de paie'), ('contract', 'Contrat'), ('certificate', 'Attestation'), ('other', 'Autre')], default='other', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(help_text='Fichier visible uniquement par cet employé et les administrateurs.', upload_to='employee_documents/%Y/%m/')),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='Employé destinataire du document.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'category'], name='core_employ_employe_c387d1_idx')],
            },
        ),
    ]
